const CounterTypes = {
  CREATE_MAP: "CREATE_MAP",
  CHANGE_DRAGGED_ELEMENT: "CHANGE_DRAGGED_ELEMENT",
  PLACE_TILE: "PLACE_TILE",
  SELECT_LAYER: "SELECT_LAYER",
  SET_BRUSH_SIZE: "SET_BRUSH_SIZE",
  ADD_LAYER: "ADD_LAYER",
  TOGGLE_GRID: "TOGGLE_GRID",
  LOAD_MAP: "LOAD_MAP",
  TOGGLE_ERASE_MODE: "TOGGLE_ERASE_MODE",
  TOGGLE_CLEAR_MODE: "TOGGLE_CLEAR_MODE",
};
export default {
  ...CounterTypes,
};
